# Generated by Django 5.0.4 on 2024-06-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid_app', '0002_remove_dashboarditem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image_gallery',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
    ]
